#!/bin/zsh

PC=`acpi -b | awk '{print $4}' | tr -d '%,'`
STATUS=`acpi -b | awk '{print $3}' | tr -d ','`

if [[ -v PC ]] then;
    if [[ $PC -lt 25 ]] then;
        echo -n "#[fg=red]$PC% "
    elif [[ $PC -lt 70 ]] then;
        echo -n "#[fg=yellow]$PC% "
    else
        echo -n "#[fg=green]$PC% "
    fi

    if [[ $STATUS == "Discharging" ]] then;
        echo -n "↓"
    elif [[ $STATUS == "Charging" ]] then;
        echo -n "↑"
    fi
fi
echo -n "#[default]"

